# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - medcost

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://medcost.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_49255b98acbb4bb591ff2b43fee350e1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a948f5c5ed034701b8dbc3e643d3fe10 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: medcost.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49255b98acbb4bb591ff2b43fee350e1 }}/med-charge-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'medcost'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5efd2a5d11aa4e5a9db06772c38ce86f }}
        images: 'medcost.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_49255b98acbb4bb591ff2b43fee350e1 }}/med-charge-app:${{ github.sha }}'